SRC_DIR = src
OUT_DIR = out
DIST_DIR = dist

# Embedded IOP modules are generated here by bin2c.
MODULES_DIR = $(OUT_DIR)/modules
EE_C_DIR = $(MODULES_DIR)/

EE_BIN = $(OUT_DIR)/disc-launcher-raw.elf
EE_BIN_STRIPPED = $(OUT_DIR)/disc-launcher-stripped.elf
EE_BIN_PACKED = $(DIST_DIR)/disc-launcher.elf

EE_OBJS = $(OUT_DIR)/main.o $(OUT_DIR)/cnf_lite.o $(EE_C_DIR)ps2dev9.o $(EE_C_DIR)ps2atad.o $(EE_C_DIR)ps2fs.o $(EE_C_DIR)ps2hdd.o $(EE_C_DIR)iomanx.o $(EE_C_DIR)filexio.o $(EE_C_DIR)usbd.o $(EE_C_DIR)usbmass.o

EE_INCS := -I$(PS2SDK)/ports/include -I$(PS2SDK)/ee/include -I$(PS2SDK)/common/include -I$(SRC_DIR) -I.
EE_GPVAL = -G0
EE_CFLAGS = -O2 -D_EE -Os -mgpopt -mno-gpopt $(EE_GPVAL) -Wall $(EE_INCS) -Wno-stringop-truncation -MMD -MP
EE_LDFLAGS = -L$(PS2SDK)/ee/lib
EE_LIBS += -lfileXio -lpatches -lelf-loader-nocolour -L$(PS2SDK)/ports/lib -ldebug -lpad
EE_NEWLIB_NANO ?= 1
EE_COMPACT_EXECUTABLE ?= 1

BIN2C = $(PS2SDK)/bin/bin2c

.PHONY: all clean

all: $(EE_BIN_PACKED) $(DIST_DIR)/disc-launcher.cnf

$(MODULES_DIR):
	mkdir -p $@

# Sources live in $(SRC_DIR) but objects belong in $(OUT_DIR); the SDK's own
# %.o: %.c rule only handles objects sitting next to their source.
$(OUT_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(@D)
	$(EE_CC) $(EE_CFLAGS) $(EE_INCS) -c $< -o $@

$(EE_BIN_STRIPPED): $(EE_BIN)
	@echo "Stripping..."
	$(EE_STRIP) -o $@ $<

$(EE_BIN_PACKED): $(EE_BIN_STRIPPED)
	@echo "Compressing..."
	@mkdir -p $(@D)
	ps2-packer $< $@

# Ship the sample config next to the ELF, so $(DIST_DIR) can be copied as-is.
$(DIST_DIR)/disc-launcher.cnf: disc-launcher.cnf
	@mkdir -p $(@D)
	cp $< $@

clean:
	rm -rf $(OUT_DIR) $(DIST_DIR)

$(EE_C_DIR)ps2dev9.c: $(PS2SDK)/iop/irx/ps2dev9.irx | $(MODULES_DIR)
	$(BIN2C) $< $@ ps2dev9_irx

$(EE_C_DIR)ps2atad.c: $(PS2SDK)/iop/irx/ps2atad.irx | $(MODULES_DIR)
	$(BIN2C) $< $@ ps2atad_irx

$(EE_C_DIR)ps2fs.c: $(PS2SDK)/iop/irx/ps2fs.irx | $(MODULES_DIR)
	$(BIN2C) $< $@ ps2fs_irx

$(EE_C_DIR)ps2hdd.c: $(PS2SDK)/iop/irx/ps2hdd-osd.irx | $(MODULES_DIR)
	$(BIN2C) $< $@ ps2hdd_irx

$(EE_C_DIR)iomanx.c: $(PS2SDK)/iop/irx/iomanX.irx | $(MODULES_DIR)
	$(BIN2C) $< $@ iomanx_irx

$(EE_C_DIR)usbd.c: $(PS2SDK)/iop/irx/usbd.irx | $(MODULES_DIR)
	$(BIN2C) $< $@ usbd_irx

$(EE_C_DIR)usbmass.c: $(PS2SDK)/iop/irx/usbmass_bd.irx | $(MODULES_DIR)
	$(BIN2C) $< $@ usbmass_bd_irx

$(EE_C_DIR)filexio.c: $(PS2SDK)/iop/irx/fileXio.irx | $(MODULES_DIR)
	$(BIN2C) $< $@ filexio_irx

include $(PS2SDK)/Defs.make
include $(PS2SDK)/samples/Makefile.eeglobal

# Header dependencies generated by -MMD.
-include $(wildcard $(OUT_DIR)/*.d $(MODULES_DIR)/*.d)
